#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Bootstrap Composer autoloader
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel
$argvInput = new ArgvInput;
$app = require __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand($argvInput);

exit($status);
