export type Locale = "lt" | "en" | "ru";

export const siteCopy = {
  lt: {
    localeName: "Lietuvių",
    nav: { home: "Pradžia", brain: "Smegenų veikla", help: "Kuo gali padėti", method: "Metodas", session: "Konsultacija", about: "Apie", resources: "Ištekliai", sleep: "Sleep Track", frequencies: "Muzika klausymui", faq: "DUK", shop: "Parduotuvė", contact: "Kontaktai", call: "Pirmas pokalbis", menu: "Atverti meniu", close: "Uždaryti meniu", brandLine: "Klinikinė hipnoterapija", primaryLabel: "Pagrindinė navigacija", mobileLabel: "Mobilioji navigacija", languageLabel: "Kalba" },
    hero: {
      eyebrow: "Išgirsti kūną. Suprasti save.",
      titleBefore: "Kad pasikeistumėte, nereikia ",
      titleAccent: "kovoti",
      titleAfter: " su savimi.",
      lead: "Kūnas nėra kliūtis — jis jūsų sąjungininkas. Galime sąmoningai keisti savo reakcijas, tačiau kūno nereikia nugalėti. Jis nuolat siunčia signalus, o hipnoterapija gali padėti sustoti, juos išgirsti ir pasirinkti naują atsaką.",
      primary: "Sulėtėti ir įsiklausyti į save",
      secondary: "Kaip tai veikia",
      qualified: "Diplomuota specialistė",
      uk: "Išsilavinimas įgytas Jungtinėje Karalystėje",
      science: "Mokslu grįstas požiūris",
      scienceText: "į dėmesį, kūno signalus ir pokytį",
      imageAlt: "Švytintis žmogaus profilis, vaizduojantis smegenų reakcijas ir sąmoningą pasirinkimą",
    },
    principles: ["Be vertinimo", "Aiškus tikslas", "Individualus tempas", "Konfidencialumas"],
    concernsIntro: {
      kicker: "Kuo gali būti naudinga",
      title: "Kai kūnas kalba, bet jo signalus nustelbia kasdienis triukšmas.",
      text: "Kūno reakcijos nėra silpnumas — jos gali būti svarbi informacija. Hipnoterapija padeda sutelkti dėmesį, pastebėti įprastus atsakus ir saugioje būsenoje kurti kitokį santykį su jais.",
    },
    concerns: [
      { title: "Įtampa ir nerimas", text: "Kai mintys sukasi ratu, o kūnui sunku persijungti į ramybės būseną." },
      { title: "Miego sunkumai", text: "Kai vakare nepavyksta sulėtėti arba poilsis negrąžina jėgų." },
      { title: "Įpročiai ir elgesio pokyčiai", text: "Kai žinote, ką norite keisti, bet vien valios pastangų nepakanka." },
      { title: "Pasitikėjimas ir veiklos kokybė", text: "Kai vidiniai stabdžiai trukdo atsiskleisti, kalbėti ar siekti rezultato." },
    ],
    careNote: "Hipnoterapija nėra skubios pagalbos ar medicininio gydymo pakaitalas. Tinkamumas įvertinamas individualiai.",
    method: {
      kicker: "Metodas",
      title: "Sukurk savo pasaulį ir pasiek savo tikslus.",
      text: "Oksanos darbas remiasi Jungtinėje Karalystėje įgytu išsilavinimu ir Inspiraology® mokymo kryptimi. Dėmesio sutelkimas, sprendimų fokusas ir šiuolaikinis supratimas apie smegenis bei elgesį padeda tyrinėti ryšį tarp minties, kūno signalo ir pasirinkto atsako.",
      source: "Apie Inspiraology metodiką",
      steps: [
        { title: "Sustoti", text: "Aiškiai įvardijame tikslą ir sumažiname išorinį bei vidinį triukšmą, kad atsirastų erdvės pastebėti save." },
        { title: "Išgirsti", text: "Sutelktas dėmesys padeda atpažinti kūno signalus, automatines reakcijas ir tai, ką jos gali mėginti apsaugoti." },
        { title: "Pasirinkti", text: "Kuriame sąmoningesnį, tikslui palankų atsaką ir praktiškus žingsnius, kuriuos galima įtvirtinti kasdienybėje." },
      ],
    },
    session: {
      kicker: "Kaip vyksta konsultacija",
      title: "Jūs valdote pasirinkimus, o kūno signalai padeda suprasti kryptį.",
      points: [
        "Pirmiausia kalbamės apie jūsų tikslą ir lūkesčius.",
        "Paaiškinama, kas vyks ir ko galite tikėtis.",
        "Hipnozės būsena kuriama palaipsniui, be spaudimo.",
        "Po sesijos aptariame patirtį ir tolesnius žingsnius.",
      ],
      explanation: "Daugelis simptomų, su kuriais susiduriame, gali būti ilgai ir nepastebimai kaupto streso atspindžiai. Hipnoterapija gali padėti kūnui paleisti šią nematomą naštą. Grįždami į sveikesnį ir harmoningesnį gyvenimo ritmą, ne tik mažiname nerimą — kuriame saugią erdvę, kurioje stresui nebereikia valdyti kūno reakcijų.",
      quote: "Kūnas nėra sukurtas trukdyti. Jis nuolat mėgina padėti — kartais pirmas žingsnis yra ne jį nutildyti, o išgirsti.",
    },
    about: {
      kicker: "Apie specialistę",
      title: "Profesionalumas, kuris leidžia jaustis žmogumi.",
      lead: "Oksana Sakalauskienė — diplomuota klinikinės hipnoterapijos specialistė, profesinį išsilavinimą įgijusi Jungtinėje Karalystėje.",
      text: "Jos darbo principas paprastas: žmogaus ir kūno nereikia „taisyti“ ar versti paklusti. Reikia saugios erdvės, aiškaus tikslo ir tinkamų priemonių, padedančių išgirsti signalus bei pasiekti jau turimus vidinius resursus. Konsultacijose dera struktūra, empatija ir pagarba kiekvieno žmogaus tempui.",
      credentials: ["Diplomą patvirtinantis išsilavinimas UK", "Inspiraology® mokymo kryptis", "Šiuolaikinis, praktiškas požiūris"],
    },
    faqIntro: { kicker: "Dažniausi klausimai", title: "Prieš pirmą žingsnį — aiškūs atsakymai.", text: "Smalsumas ir abejonės yra natūrali proceso pradžia." },
    faqs: [
      { question: "Ar hipnozės metu prarandama kontrolė?", answer: "Ne. Hipnoterapijos metu išliekate sąmoningi, girdite specialistę ir galite bet kada sustabdyti procesą. Tai sutelkto dėmesio ir gilaus atsipalaidavimo būsena, o ne miegas ar kontrolės perdavimas." },
      { question: "Ar mane galima priversti daryti tai, ko nenoriu?", answer: "Ne. Jūsų vertybės, ribos ir pasirinkimai išlieka. Terapinis darbas vyksta bendradarbiaujant ir tik dėl iš anksto aptarto tikslo." },
      { question: "Kiek konsultacijų gali reikėti?", answer: "Tai priklauso nuo tikslo, situacijos ir individualios reakcijos. Pirmojo pokalbio metu aptariamas realistiškas planas, o eiga reguliariai peržiūrima — be pažadų apie garantuotą rezultatą." },
      { question: "Ar reikia mokėti atsipalaiduoti?", answer: "Ne. Smalsumo ir noro bendradarbiauti pakanka. Oksana procesą paaiškina paprastai ir padeda rasti jums tinkamą tempą." },
      { question: "Ar hipnoterapija pakeičia gydymą?", answer: "Ne. Hipnoterapija nėra gydytojo, psichologo ar psichiatro diagnozės ir gydymo pakaitalas. Sprendimus dėl gydymo priimkite tik su savo sveikatos priežiūros specialistu." },
    ],
    conversation: {
      kicker: "Pirmas žingsnis",
      title: "Pradėkime nuo ramaus, neįpareigojančio pokalbio.",
      text: "Trumpai aptarsime, ko norėtumėte pasiekti, atsakysime į klausimus ir įvertinsime, ar hipnoterapija jums tinka. Konsultacijos formatas ir laikas derinami individualiai.",
      phoneLabel: "Skambinti Oksanai",
    },
    disclaimer: "Informacija svetainėje yra šviečiamojo pobūdžio ir nepakeičia individualios sveikatos specialisto konsultacijos.",
    shop: {
      eyebrow: "Konsultacijų parduotuvė",
      title: "Pasirinkite jums tinkamą pradžią.",
      lead: "Pasirinkite pasiūlymą, įdėkite jį į krepšelį ir išsiųskite užklausą Oksanai el. paštu. Laikas bei galutinė paslaugos apimtis suderinami individualiai.",
      price: "Kaina",
      order: "Rašyti el. paštu",
      back: "Grįžti į pagrindinį puslapį",
      note: "Galutinė paslaugos apimtis ir kaina patvirtinama pokalbio metu.",
      products: [
        { badge: "Pirmas žingsnis", title: "Individuali konsultacija", text: "Viena individuali sesija konkrečiam tikslui aptarti ir terapiniam darbui pradėti.", meta: "1 konsultacija", price: "132 €" },
        { badge: "4 savaičių programa", title: "Darbas su baime ar fobija", text: "Struktūruota keturių savaičių programa įsisenėjusiai baimei ar fobijai nagrinėti.", meta: "Individuali programa", price: "600 €" },
        { badge: "Viena kryptinga sesija", title: "Metimas rūkyti", text: "Individuali kryptinga hipnoterapijos sesija žmogui, apsisprendusiam mesti rūkyti.", meta: "1 konsultacija", price: "520 €" },
        { badge: "Knyga", title: "Mokslu grįstas pokytis", text: "Praktinė knyga apie smegenų reakcijas, sutelktą dėmesį ir pokytį be kovos su savimi.", meta: "Spausdinta knyga", price: "30 €" },
        { badge: "Grupėms", title: "Hipnoterapijos mokymai su Matthew Cahill", text: "Matthew Cahill vedami hipnoterapijos mokymai grupėms. Formatas, vieta, datos ir programa patvirtinami atskiru susitarimu.", meta: "Mokymus veda Matthew Cahill", price: "Kaina derinama" },
      ],
    },
  },
  en: {
    localeName: "English",
    nav: { home: "Home", brain: "Brain explanation", help: "How it may help", method: "Method", session: "Consultation", about: "About", resources: "Resources", sleep: "Sleep Track", frequencies: "Music for listening", faq: "FAQ", shop: "Shop", contact: "Contact", call: "First conversation", menu: "Open menu", close: "Close menu", brandLine: "Clinical hypnotherapy", primaryLabel: "Primary navigation", mobileLabel: "Mobile navigation", languageLabel: "Language" },
    hero: {
      eyebrow: "Hear the body. Understand yourself.",
      titleBefore: "You do not have to ", titleAccent: "fight", titleAfter: " yourself to change.",
      lead: "Your body is not an obstacle — it is your ally. We can consciously change our responses, but the body does not need to be defeated. It continually sends signals, and hypnotherapy may help you pause, hear them and choose a new response.",
      primary: "Slow down and listen within", secondary: "How it works", qualified: "Qualified practitioner", uk: "Professionally trained in the United Kingdom", science: "A science-informed approach", scienceText: "to attention, body signals and change", imageAlt: "A luminous human profile representing brain responses and conscious choice",
    },
    principles: ["Without judgement", "A clear goal", "Your own pace", "Confidentiality"],
    concernsIntro: { kicker: "How it may help", title: "When the body speaks, but everyday noise drowns out its signals.", text: "Bodily responses are not weakness — they may carry useful information. Hypnotherapy can help focus attention, notice habitual responses and develop a different relationship with them in a safe state." },
    concerns: [
      { title: "Stress and anxiety", text: "When thoughts keep circling and the body struggles to return to calm." },
      { title: "Sleep difficulties", text: "When it is hard to slow down in the evening or rest does not restore your energy." },
      { title: "Habits and behaviour change", text: "When you know what you want to change, but willpower alone is not enough." },
      { title: "Confidence and performance", text: "When inner barriers make it difficult to speak, perform or move towards a goal." },
    ],
    careNote: "Hypnotherapy is not a substitute for emergency support or medical treatment. Suitability is assessed individually.",
    method: {
      kicker: "Method", title: "Create your world and achieve your goals.",
      text: "Oksana’s work is grounded in her UK education and the Inspiraology® training approach. Focused attention, solution-focused practice and a modern understanding of the brain and behaviour help explore the link between a thought, a bodily signal and a chosen response.", source: "About the Inspiraology approach",
      steps: [
        { title: "Pause", text: "We clarify the goal and reduce external and internal noise, creating space to notice what is happening." },
        { title: "Listen", text: "Focused attention helps recognise bodily signals, automatic responses and what they may be trying to protect." },
        { title: "Choose", text: "We develop a more conscious, goal-supporting response and practical steps that can be reinforced in daily life." },
      ],
    },
    session: { kicker: "What a session is like", title: "You direct your choices; the body’s signals help illuminate the way.", points: ["We begin by discussing your goal and expectations.", "You receive a clear explanation of what will happen.", "The hypnotic state is developed gradually and without pressure.", "Afterwards, we discuss the experience and next steps."], explanation: "Many symptoms we encounter may reflect stress that has accumulated quietly over time. Hypnotherapy can help the body release some of this unseen burden. As a healthier and more harmonious rhythm returns, the aim is not only to ease anxiety, but to create a safer inner space where stress no longer needs to direct the body’s responses.", quote: "The body is not designed to stand in your way. It is continually trying to help — sometimes the first step is not to silence it, but to listen." },
    about: { kicker: "About the practitioner", title: "Professional care that still feels human.", lead: "Oksana Sakalauskienė is a qualified clinical hypnotherapy practitioner who completed her professional education in the United Kingdom.", text: "Her principle is simple: neither a person nor their body needs to be ‘fixed’ or forced into submission. A safe space, a clear goal and appropriate tools can help people hear their signals and access the inner resources they already have. Her sessions combine structure, empathy and respect for each person’s pace.", credentials: ["UK diploma-level education", "Inspiraology® training approach", "Modern, practical perspective"] },
    faqIntro: { kicker: "Frequently asked questions", title: "Clear answers before your first step.", text: "Curiosity and uncertainty are a natural place to begin." },
    faqs: [
      { question: "Will I lose control under hypnosis?", answer: "No. You remain aware, can hear the practitioner and may stop the process at any time. Hypnosis is a state of focused attention and deep relaxation, not sleep or surrendering control." },
      { question: "Can I be made to do something I do not want?", answer: "No. Your values, boundaries and choices remain intact. Therapeutic work is collaborative and follows an agreed goal." },
      { question: "How many sessions might I need?", answer: "It depends on your goal, circumstances and individual response. A realistic plan is discussed during the first conversation and reviewed as you progress, without guaranteed-outcome claims." },
      { question: "Do I need to be good at relaxing?", answer: "No. Curiosity and willingness to engage are enough. Oksana explains the process clearly and helps you find a pace that works for you." },
      { question: "Does hypnotherapy replace medical treatment?", answer: "No. It does not replace diagnosis or treatment from a doctor, psychologist or psychiatrist. Treatment decisions should only be made with your healthcare professional." },
    ],
    conversation: { kicker: "First step", title: "Let’s begin with a calm, no-obligation conversation.", text: "We will briefly discuss what you would like to achieve, answer your questions and consider whether hypnotherapy is suitable for you. The session format and time are agreed individually.", phoneLabel: "Call Oksana" },
    disclaimer: "The information on this website is educational and does not replace an individual consultation with a healthcare professional.",
    shop: { eyebrow: "Consultation shop", title: "Choose the right place to begin.", lead: "Choose an option, add it to your cart and email your enquiry to Oksana. Timing and the final scope of the service are agreed individually.", price: "Price", order: "Email Oksana", back: "Back to the main page", note: "The final scope of the service is confirmed during your conversation.", products: [
      { badge: "First step", title: "Individual consultation", text: "One individual session to clarify a specific goal and begin therapeutic work.", meta: "1 consultation", price: "132 €" },
      { badge: "Four-week programme", title: "Working with a fear or phobia", text: "A structured four-week programme for exploring an entrenched fear or phobia.", meta: "Individual programme", price: "600 €" },
      { badge: "One focused session", title: "Smoking cessation", text: "An individual, focused hypnotherapy session for someone who has decided to stop smoking.", meta: "1 consultation", price: "520 €" },
      { badge: "Book", title: "Science-informed change", text: "A practical book about brain responses, focused attention and change without fighting yourself.", meta: "Printed book", price: "30 €" },
      { badge: "For groups", title: "Hypnotherapy training with Matthew Cahill", text: "Group hypnotherapy training delivered by Matthew Cahill. Format, location, dates and programme are confirmed by separate agreement.", meta: "Delivered by Matthew Cahill", price: "Price by agreement" },
    ] },
  },
  ru: {
    localeName: "Русский",
    nav: { home: "Главная", brain: "Объяснение работы мозга", help: "Чем может помочь", method: "Метод", session: "Консультация", about: "О специалисте", resources: "Материалы", sleep: "Sleep Track", frequencies: "Музыка для прослушивания", faq: "Вопросы", shop: "Магазин", contact: "Контакты", call: "Первая беседа", menu: "Открыть меню", close: "Закрыть меню", brandLine: "Клиническая гипнотерапия", primaryLabel: "Основная навигация", mobileLabel: "Мобильная навигация", languageLabel: "Язык" },
    hero: {
      eyebrow: "Услышать тело. Понять себя.",
      titleBefore: "Чтобы измениться, не нужно ", titleAccent: "бороться", titleAfter: " с собой.",
      lead: "Тело — не препятствие, а ваш союзник. Мы можем сознательно менять свои реакции, но тело не нужно побеждать. Оно постоянно посылает сигналы, а гипнотерапия может помочь остановиться, услышать их и выбрать новый ответ.",
      primary: "Замедлиться и выслушать себя", secondary: "Как это работает", qualified: "Дипломированный специалист", uk: "Профессиональное образование получено в Великобритании", science: "Научно обоснованный подход", scienceText: "к вниманию, сигналам тела и изменениям", imageAlt: "Светящийся профиль человека, символизирующий реакции мозга и осознанный выбор",
    },
    principles: ["Без осуждения", "Ясная цель", "Ваш собственный темп", "Конфиденциальность"],
    concernsIntro: { kicker: "Чем может быть полезно", title: "Когда тело говорит, но повседневный шум заглушает его сигналы.", text: "Телесные реакции — не слабость, а возможный источник важной информации. Гипнотерапия помогает сосредоточить внимание, заметить привычные реакции и в безопасном состоянии выстроить с ними новые отношения." },
    concerns: [
      { title: "Напряжение и тревога", text: "Когда мысли ходят по кругу, а телу трудно вернуться в спокойное состояние." },
      { title: "Проблемы со сном", text: "Когда вечером трудно замедлиться или отдых не восстанавливает силы." },
      { title: "Привычки и поведение", text: "Когда вы знаете, что хотите изменить, но одной силы воли недостаточно." },
      { title: "Уверенность и результат", text: "Когда внутренние барьеры мешают проявить себя, говорить или двигаться к цели." },
    ],
    careNote: "Гипнотерапия не заменяет экстренную помощь или медицинское лечение. Возможность её применения оценивается индивидуально.",
    method: {
      kicker: "Метод", title: "Создайте свой мир и достигайте своих целей.",
      text: "Работа Оксаны основана на образовании, полученном в Великобритании, и подходе Inspiraology®. Сосредоточенное внимание, фокус на решениях и современное понимание мозга и поведения помогают исследовать связь между мыслью, телесным сигналом и выбранной реакцией.", source: "О методике Inspiraology",
      steps: [
        { title: "Остановиться", text: "Мы уточняем цель и уменьшаем внешний и внутренний шум, освобождая пространство для наблюдения за собой." },
        { title: "Услышать", text: "Сосредоточенное внимание помогает распознать сигналы тела, автоматические реакции и то, что они могут пытаться защитить." },
        { title: "Выбрать", text: "Мы формируем более осознанную, поддерживающую цель реакцию и практические шаги для повседневной жизни." },
      ],
    },
    session: { kicker: "Как проходит консультация", title: "Вы управляете выбором, а сигналы тела помогают увидеть направление.", points: ["Сначала мы обсуждаем вашу цель и ожидания.", "Вы получаете понятное объяснение каждого этапа.", "Гипнотическое состояние создаётся постепенно и без давления.", "После сеанса мы обсуждаем опыт и следующие шаги."], explanation: "Многие симптомы, с которыми мы сталкиваемся, — это отпечатки стресса, который годами незаметно накапливался внутри. Гипнотерапия может помочь организму сбросить этот невидимый груз. Возвращаясь к более здоровому и гармоничному ритму жизни, мы не просто снижаем тревогу — мы создаём безопасное пространство, где у стресса больше нет необходимости управлять реакциями тела.", quote: "Тело создано не для того, чтобы мешать. Оно постоянно пытается помочь — иногда первый шаг не заглушить его, а услышать." },
    about: { kicker: "О специалисте", title: "Профессионализм, в котором остаётся человечность.", lead: "Оксана Сакалаускене — дипломированный специалист по клинической гипнотерапии, получившая профессиональное образование в Великобритании.", text: "Её принцип прост: ни человека, ни его тело не нужно «исправлять» или заставлять подчиняться. Безопасное пространство, ясная цель и подходящие инструменты помогают услышать сигналы и обратиться к уже существующим внутренним ресурсам. В консультациях сочетаются структура, эмпатия и уважение к индивидуальному темпу.", credentials: ["Дипломное образование в Великобритании", "Подход Inspiraology®", "Современный практический взгляд"] },
    faqIntro: { kicker: "Частые вопросы", title: "Ясные ответы перед первым шагом.", text: "Любопытство и сомнения — естественное начало процесса." },
    faqs: [
      { question: "Теряется ли контроль во время гипноза?", answer: "Нет. Вы сохраняете сознание, слышите специалиста и можете остановить процесс в любой момент. Это состояние сфокусированного внимания и глубокого расслабления, а не сон или передача контроля." },
      { question: "Можно ли заставить меня делать то, чего я не хочу?", answer: "Нет. Ваши ценности, границы и выбор сохраняются. Терапевтическая работа строится на сотрудничестве и заранее согласованной цели." },
      { question: "Сколько консультаций может понадобиться?", answer: "Это зависит от цели, ситуации и индивидуальной реакции. Реалистичный план обсуждается во время первой беседы и пересматривается по мере продвижения — без обещаний гарантированного результата." },
      { question: "Нужно ли уметь хорошо расслабляться?", answer: "Нет. Достаточно любопытства и готовности сотрудничать. Оксана понятно объясняет процесс и помогает найти комфортный темп." },
      { question: "Заменяет ли гипнотерапия лечение?", answer: "Нет. Она не заменяет диагностику и лечение врача, психолога или психиатра. Решения о лечении следует принимать только совместно с вашим медицинским специалистом." },
    ],
    conversation: { kicker: "Первый шаг", title: "Начнём со спокойной беседы без обязательств.", text: "Мы кратко обсудим, чего вы хотите достичь, ответим на вопросы и оценим, подходит ли вам гипнотерапия. Формат и время консультации согласуются индивидуально.", phoneLabel: "Позвонить Оксане" },
    disclaimer: "Информация на сайте носит образовательный характер и не заменяет индивидуальную консультацию медицинского специалиста.",
    shop: { eyebrow: "Магазин консультаций", title: "Выберите подходящее начало.", lead: "Выберите предложение, добавьте его в корзину и отправьте запрос Оксане по электронной почте. Время и окончательный объём услуги согласуются индивидуально.", price: "Цена", order: "Написать Оксане", back: "Вернуться на главную", note: "Окончательный объём услуги подтверждается во время разговора.", products: [
      { badge: "Первый шаг", title: "Индивидуальная консультация", text: "Одна индивидуальная сессия, чтобы определить конкретную цель и начать терапевтическую работу.", meta: "1 консультация", price: "132 €" },
      { badge: "Программа на 4 недели", title: "Работа со страхом или фобией", text: "Структурированная четырёхнедельная программа для работы с устойчивым страхом или фобией.", meta: "Индивидуальная программа", price: "600 €" },
      { badge: "Одна целевая сессия", title: "Отказ от курения", text: "Индивидуальная целевая сессия гипнотерапии для человека, решившего отказаться от курения.", meta: "1 консультация", price: "520 €" },
      { badge: "Книга", title: "Научно обоснованные изменения", text: "Практическая книга о реакциях мозга, сфокусированном внимании и изменениях без борьбы с собой.", meta: "Печатная книга", price: "30 €" },
      { badge: "Для групп", title: "Обучение гипнотерапии с Matthew Cahill", text: "Обучение гипнотерапии для групп проводит Matthew Cahill. Формат, место, даты и программа подтверждаются отдельным соглашением.", meta: "Обучение проводит Matthew Cahill", price: "Цена по согласованию" },
    ] },
  },
} as const;

export const homePaths: Record<Locale, string> = { lt: "/", en: "/en", ru: "/ru" };
export const shopPaths: Record<Locale, string> = { lt: "/shop", en: "/en/shop", ru: "/ru/shop" };
